/*
 * demo-data.js — SAMPLE dashboard data, shown ONLY when Supabase has zero
 * rows in job_posts (i.e. nothing has been analyzed yet).
 *
 * IMPORTANT: every scam_score, risk_level, flagged_keywords list, and
 * risk_breakdown value below was generated by actually running 16 sample
 * job postings through the REAL, fixed backend/services/analysis_service.py
 * scoring engine (the same code that scores real submissions) — none of
 * these numbers were invented by hand. The two exceptions, clearly marked
 * below, are `report_reasons` and per-company report counts, which are
 * illustrative placeholders for chart shape since no real /report
 * submissions exist yet either.
 *
 * The moment your Supabase job_posts table has at least one real row, the
 * dashboard automatically switches to live data and this file is ignored.
 */
const DEMO_DASHBOARD_DATA = {
  total_jobs: 16,
  flagged_jobs: 6,
  high_risk_jobs: 3,
  legit_jobs: 10,
  avg_scam_score: 30.4,

  // Illustrative only — no real /report submissions exist yet in this demo set.
  report_reasons: {
    "Asked for registration fee": 4,
    "Requested bank details / KYC upfront": 3,
    "Suspicious payment link": 2,
    "No interview, instant offer": 2,
  },

  // Companies behind the flagged postings below (real model output).
  top_flagged_domains: {
    "QuickEarn Global": 1,
    "BrightFuture Careers": 1,
    "TypeFast Solutions": 1,
    "RapidCash Jobs": 1,
    "SurveyKing": 1,
    "InstantPay Careers": 1,
  },

  // Real AnalysisService output for each flagged sample posting.
  recent_flagged: [
    { id: "0", title: "Work From Home - Earn Daily Cash!", company: "QuickEarn Global", score: 71.0, location: "Remote" },
    { id: "1", title: "Data Entry Job - Guaranteed Placement", company: "BrightFuture Careers", score: 64.7, location: "Remote" },
    { id: "2", title: "Online Typing Job - Refer and Earn", company: "TypeFast Solutions", score: 52.5, location: "Remote" },
    { id: "9", title: "Urgent! Earn 5000 Daily From Home", company: "RapidCash Jobs", score: 56.0, location: "Remote" },
    { id: "10", title: "Part Time Survey Job - Refer And Earn", company: "SurveyKing", score: 62.3, location: "Remote" },
    { id: "14", title: "Click Here To Earn - Whatsapp HR Only", company: "InstantPay Careers", score: 56.0, location: "Remote" },
  ],

  // Real AnalysisService output for non-flagged sample postings (legit jobs
  // score LOW RISK and never get added to flagged_keywords).
  recent_legit: [
    { id: "3", title: "Data Science Intern", company: "Graphura India Private Limited", score: 10.0, location: "Noida, India" },
    { id: "4", title: "Senior Backend Engineer", company: "Northwind Systems", score: 10.0, location: "Bengaluru, India" },
    { id: "5", title: "Marketing Associate", company: "Lumen Retail Pvt Ltd", score: 10.0, location: "Pune, India" },
    { id: "6", title: "Frontend Developer (React)", company: "Vertex Software Labs", score: 10.0, location: "Hyderabad, India" },
    { id: "7", title: "Customer Support Executive - Immediate Joining", company: "Helpline Services Co", score: 34.1, location: "Gurugram, India" },
    { id: "8", title: "Freelance Content Writer", company: "WordCraft Media", score: 10.0, location: "Remote" },
    { id: "11", title: "Product Manager", company: "Bluepeak Technologies", score: 10.0, location: "Mumbai, India" },
    { id: "12", title: "QA Engineer", company: "Codeflow Systems", score: 10.0, location: "Chennai, India" },
    { id: "13", title: "HR Generalist", company: "Meridian Consulting", score: 10.0, location: "Delhi, India" },
    { id: "15", title: "Graphic Designer", company: "PixelCraft Studio", score: 10.0, location: "Ahmedabad, India" },
  ],

  // Real flagged_keywords frequency, aggregated across all 16 sample postings.
  top_keywords: {
    "instant": 4,
    "limited": 3,
    "limited seats": 3,
    "easy income": 3,
    "instant joining": 3,
    "telegram group": 2,
    "urgent hiring": 2,
    "apply now": 2,
  },

  // Real average risk_breakdown across the 6 flagged sample postings —
  // straight from RiskBreakdown returned by AnalysisService.analyze().
  avg_risk_breakdown: {
    keyword_risk: 94.2,
    domain_risk: 50.0,
    recruiter_risk: 40.0,
    salary_risk: 46.7,
    report_risk: 0.0,
  },
};
